# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
    - stage: Build
      displayName: Build Stage
      jobs:
          - job: Build
            displayName: Build
            pool:
              vmImage: ubuntu-latest
            steps:
              - task: replacetokens@5
                displayName: 'Replace tokens in appsettings.json'
                inputs:
                  rootDirectory: '$(build.sourcesdirectory)/src/MyHealth.Web'
                  targetFiles: appsettings.json
                  escapeType: none

              - task: replacetokens@5
                displayName: 'Replace tokens in mhc-aks.yaml'
                inputs:
                  targetFiles: 'mhc-aks.yaml'
                  escapeType: none
                  tokenPrefix: '__'
                  tokenSuffix: '__'
              - task: DockerCompose@1
                inputs:
                  containerregistrytype: 'Azure Container Registry'
                  azureSubscription: 'Azure subscription 1 (8e5493a7-1eae-4169-adfd-8ec3bb80365a)'
                  azureContainerRegistry: '{"loginServer":"acr810.azurecr.io", "id" : "/subscriptions/8e5493a7-1eae-4169-adfd-8ec3bb80365a/resourceGroups/testvm/providers/Microsoft.ContainerRegistry/registries/acr810"}'
                  dockerComposeFile: '**/docker-compose.yml'
                  action: 'Run a Docker Compose command'
        
              - task: DockerCompose@1
                inputs:
                  containerregistrytype: 'Azure Container Registry'
                  azureSubscription: 'Azure subscription 1 (8e5493a7-1eae-4169-adfd-8ec3bb80365a)'
                  azureContainerRegistry: '{"loginServer":"acr810.azurecr.io", "id" : "/subscriptions/8e5493a7-1eae-4169-adfd-8ec3bb80365a/resourceGroups/testvm/providers/Microsoft.ContainerRegistry/registries/acr810"}'
                  dockerComposeFile: '**/docker-compose.yml'
                  action: 'Push services'

              - task: CopyFiles@2
                displayName: 'Copy Files'
                inputs:
                  Contents: |
                   **/mhc-aks.yaml
                   **/*.dacpac
     
                  TargetFolder: '$(Build.ArtifactStagingDirectory)'

              - task: PublishBuildArtifacts@1
                displayName: 'Publish Artifact'
                inputs:
                  ArtifactName: deploy
 
  


